apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: edge-stack-listener-443
  namespace: ambassador
spec:
  port: 443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
